// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Benefit documents */
interface BenefitDocumentData {
  /**
   * Name field in *Benefit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField;
  /**
   * Benefit ID field in *Benefit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter benefit_id (API)...
   * - **API ID Path**: benefit.benefit_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  benefit_id: prismic.KeyTextField;
  /**
   * Partner field in *Benefit*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.partner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  partner: prismic.RelationField<"partner">;
  /**
   * Code Type field in *Benefit*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.code_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  code_type: prismic.SelectField<"codes" | "code" | "link">;
  /**
   * Short Description field in *Benefit*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  short_description: prismic.RichTextField;
  /**
   * Date Start field in *Benefit*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.date_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date_start: prismic.DateField;
  /**
   * Date End field in *Benefit*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.date_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  date_end: prismic.DateField;
  /**
   * CTA Text field in *Benefit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  cta_text: prismic.KeyTextField;
  /**
   * Uploads field in *Benefit*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.uploads[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  uploads: prismic.GroupField<Simplify<BenefitDocumentDataUploadsItem>>;
  /**
   * Slice Zone field in *Benefit*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<BenefitDocumentDataSlicesSlice>;
}
/**
 * Item in Benefit → Uploads
 *
 */
export interface BenefitDocumentDataUploadsItem {
  /**
   * file field in *Benefit → Uploads*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: benefit.uploads[].file
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  file: prismic.LinkField;
}
/**
 * Slice for *Benefit → Slice Zone*
 *
 */
type BenefitDocumentDataSlicesSlice = TermsSlice | TextSlice;
/**
 * Benefit document from Prismic
 *
 * - **API ID**: `benefit`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BenefitDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BenefitDocumentData>,
    "benefit",
    Lang
  >;
/** Content for Partner documents */
interface PartnerDocumentData {
  /**
   * Name field in *Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismic.KeyTextField;
  /**
   * Country Code field in *Partner*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.country_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  country_code: prismic.SelectField<"hr" | "rs" | "si">;
  /**
   * Icon field in *Partner*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismic.ImageField<"thumb">;
  /**
   * Short Description field in *Partner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.short_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  short_description: prismic.RichTextField;
  /**
   * Header Title field in *Partner*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.header_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  header_title: prismic.KeyTextField;
  /**
   * Header Text field in *Partner*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.header_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  header_text: prismic.RichTextField;
  /**
   * Header Color field in *Partner*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.header_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  header_color: prismic.ColorField;
  /**
   * Header Text Color field in *Partner*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.header_color_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  header_color_text: prismic.SelectField<"white" | "black">;
  /**
   * Benefit Order field in *Partner*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.benefit_order[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  benefit_order: prismic.GroupField<
    Simplify<PartnerDocumentDataBenefitOrderItem>
  >;
  /**
   * Slice Zone field in *Partner*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PartnerDocumentDataSlicesSlice>;
}
/**
 * Item in Partner → Benefit Order
 *
 */
export interface PartnerDocumentDataBenefitOrderItem {
  /**
   * Benefit field in *Partner → Benefit Order*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: partner.benefit_order[].benefit
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  benefit: prismic.RelationField<"benefit">;
}
/**
 * Slice for *Partner → Slice Zone*
 *
 */
type PartnerDocumentDataSlicesSlice = TermsSlice;
/**
 * Partner document from Prismic
 *
 * - **API ID**: `partner`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PartnerDocumentData>,
    "partner",
    Lang
  >;
export type AllDocumentTypes = BenefitDocument | PartnerDocument;
/**
 * Primary content in Terms → Primary
 *
 */
interface TermsSliceDefaultPrimary {
  /**
   * Text field in *Terms → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: terms.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Terms Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Terms`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TermsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TermsSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Terms*
 *
 */
type TermsSliceVariation = TermsSliceDefault;
/**
 * Terms Shared Slice
 *
 * - **API ID**: `terms`
 * - **Description**: `Terms`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TermsSlice = prismic.SharedSlice<"terms", TermsSliceVariation>;
/**
 * Primary content in Text → Primary
 *
 */
interface TextSliceDefaultPrimary {
  /**
   * Text Alignment field in *Text → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an alignment...
   * - **API ID Path**: text.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  text_alignment: prismic.SelectField<"left" | "center">;
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismic.RichTextField;
}
/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Text*
 *
 */
type TextSliceVariation = TextSliceDefault;
/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: `Text`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      BenefitDocumentData,
      BenefitDocumentDataUploadsItem,
      BenefitDocumentDataSlicesSlice,
      BenefitDocument,
      PartnerDocumentData,
      PartnerDocumentDataBenefitOrderItem,
      PartnerDocumentDataSlicesSlice,
      PartnerDocument,
      AllDocumentTypes,
      TermsSliceDefaultPrimary,
      TermsSliceDefault,
      TermsSliceVariation,
      TermsSlice,
      TextSliceDefaultPrimary,
      TextSliceDefault,
      TextSliceVariation,
      TextSlice,
    };
  }
}
